// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzmzo_V4cyKJM-jVWb8jEiC8ShiAgqz8',
    appId: '1:327164246685:web:5b15bcb9d95029e487f274',
    messagingSenderId: '327164246685',
    projectId: 'patient-doctor-app-f3d8b',
    authDomain: 'patient-doctor-app-f3d8b.firebaseapp.com',
    storageBucket: 'patient-doctor-app-f3d8b.appspot.com',
    measurementId: 'G-FGZTLEEXCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnSOkZi7GkD9JBJMnTThiNqhT2Kc6fcko',
    appId: '1:327164246685:android:2772285847cc6ce987f274',
    messagingSenderId: '327164246685',
    projectId: 'patient-doctor-app-f3d8b',
    storageBucket: 'patient-doctor-app-f3d8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBspXKOxBGLvtP6iqyGkCILVHwpgfD9fFY',
    appId: '1:327164246685:ios:32f1de8b0e300d7287f274',
    messagingSenderId: '327164246685',
    projectId: 'patient-doctor-app-f3d8b',
    storageBucket: 'patient-doctor-app-f3d8b.appspot.com',
    iosBundleId: 'com.example.patientDoctorScheduleApp',
  );
}
